# Generated by Django 3.1.2 on 2020-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fechaDevolucion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fechaPrestamo',
            field=models.DateField(),
        ),
    ]
